//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class IGG_TimeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("Time");
		L.RegFunction("GetCurrentTimeStampSec", GetCurrentTimeStampSec);
		L.RegFunction("GetTimeAtStartOfCurrentFrame", GetTimeAtStartOfCurrentFrame);
		L.RegVar("Default", get_Default, null);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCurrentTimeStampSec(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			int o = IGG.Time.GetCurrentTimeStampSec();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTimeAtStartOfCurrentFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			float o = IGG.Time.GetTimeAtStartOfCurrentFrame();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Default(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, IGG.Time.Default);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

